-- Table: public.utenti

-- DROP TABLE IF EXISTS public.utenti;

CREATE TABLE IF NOT EXISTS public.utenti
(
    idutente integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    username character varying(20) COLLATE pg_catalog."default" NOT NULL,
    password character varying(20) COLLATE pg_catalog."default" NOT NULL,
    ruolo character varying(10) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT utente_pkey PRIMARY KEY (idutente),
    CONSTRAINT username UNIQUE (username)
        INCLUDE(username)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.utenti
    OWNER to postgres;
    
-- Table: public.prodotti

-- DROP TABLE IF EXISTS public.prodotti;

CREATE TABLE IF NOT EXISTS public.prodotti
(
    idprodotto integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nome character varying(20) COLLATE pg_catalog."default" NOT NULL,
    prezzo double precision NOT NULL,
    codice character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT prodotto_pkey PRIMARY KEY (idprodotto),
    CONSTRAINT codice UNIQUE (codice)
        INCLUDE(codice)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.prodotti
    OWNER to postgres;
    
-- Table: public.carrelli

-- DROP TABLE IF EXISTS public.carrelli;

CREATE TABLE IF NOT EXISTS public.carrelli
(
    idcarrello integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    idutente integer NOT NULL,
    idprodotto integer NOT NULL,
    CONSTRAINT carrello_pkey PRIMARY KEY (idcarrello),
    CONSTRAINT idprodotto FOREIGN KEY (idprodotto)
        REFERENCES public.prodotti (idprodotto) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT idutente FOREIGN KEY (idutente)
        REFERENCES public.utenti (idutente) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.carrelli
    OWNER to postgres;
    

    
INSERT INTO public.utenti(
	username, password, ruolo)
	VALUES ('admin', 'admin', 'admin');
	
INSERT INTO public.utenti(
	username, password, ruolo)
	VALUES ('luca123', '12345', 'user');

INSERT INTO public.utenti(
	username, password, ruolo)
	VALUES ('marco357', '35791', 'user');
	
INSERT INTO public.utenti(
	username, password, ruolo)
	VALUES ('giovanni789', '13579', 'user');
	
INSERT INTO public.utenti(
	username, password, ruolo)
	VALUES ('antonio135', '24680', 'user');

INSERT INTO public.utenti(
	username, password, ruolo)
	VALUES ('carlo456', '67890', 'user');
	
INSERT INTO public.utenti(
	username, password, ruolo)
	VALUES ('luigi913', '24680', 'user');
	
INSERT INTO public.utenti(
	username, password, ruolo)
	VALUES ('giacomo692', '69246', 'user');
	

INSERT INTO public.prodotti(
	nome, prezzo, codice)
	VALUES ('tavolo', 59.99, 'tav1');

INSERT INTO public.prodotti(
	nome, prezzo, codice)
	VALUES ('sedia', 20, 'sed1');

INSERT INTO public.prodotti(
	nome, prezzo, codice)
	VALUES ('tappeto', 34.89, 'tap1');
	
INSERT INTO public.prodotti(
	nome, prezzo, codice)
	VALUES ('cuscino', 11, 'cus1');
	
INSERT INTO public.prodotti(
	nome, prezzo, codice)
	VALUES ('vaso', 15, 'vas1');
	
INSERT INTO public.prodotti(
	nome, prezzo, codice)
	VALUES ('lampada', 12.90, 'lam1');
	
INSERT INTO public.prodotti(
	nome, prezzo, codice)
	VALUES ('coperta', 22.99, 'cop1');

INSERT INTO public.prodotti(
	nome, prezzo, codice)
	VALUES ('tazza', 6.80, 'taz1');
